### ISSUE TITLE
A small fix

### ISSUE THREAD

**Issue by ghost** [Tetraslam/SHFLA#1]
- Please reduce the requirement to `numpy<=2.1` to make it work with `numba==0.6`, otherwise I got a conflict
- Add a hint to install ffmpeg and set the PATH to the bin folder (on Windows).  Using the recommended `--ffmpeg-location` flag did not help
- The downloaded song did not match the specified name. Is it possible to specify a YT URL instead?

**Comment by Tetraslam** [comment]
I've patched everything you've asked for. Let me know if it looks good and I'll close the issue.

- [x] changed requirements
- [x] added ffmpeg hint to README
- [x] added support for YT URLs being pasted directly as input

Thanks for the feedback! :)

**Comment by ghost** [comment]
Thanks! There seems to be another serious change now, because I cannot see the visualization anymore, due to a CUDA error. I don't have an NVIDIA card, but it was working before:

```
(SHFLA) D:\forks\other\SHFLA>python main.py
pygame 2.6.1 (SDL 2.28.4, Python 3.12.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
D:\forks\other\SHFLA\main.py:157: ResourceWarning: unclosed file <_io.TextIOWrapper name='nul' mode='w' encoding='cp65001'>
  with contextlib.redirect_stdout(open(os.devnull, 'w')), contextlib.redirect_stderr(open(os.devnull, 'w')):
ResourceWarning: Enable tracemalloc to get the object allocation traceback
────────────────────────────────────────────────────────────────────────────────────────────────────────────────── Shoegaze Hierarchical Fractal Language Architecture ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Press Enter to use the default song or enter a song name or YouTube link.

Enter song name or YouTube link (https://www.youtube.com/watch?v=FyYMzEplnfU): https://www.youtube.com/watch?v=VrCu626AVlk
Enter the resolution as width height (e.g., '1920 1080') or press Enter for default (): 1280 960
D:\forks\other\SHFLA\main.py:181: ResourceWarning: unclosed file <_io.TextIOWrapper name='nul' mode='w' encoding='cp65001'>
  with contextlib.redirect_stdout(open(os.devnull, 'w')), contextlib.redirect_stderr(open(os.devnull, 'w')):
ResourceWarning: Enable tracemalloc to get the object allocation traceback
Downloading and processing audio...
D:\forks\other\SHFLA\.venv\Lib\site-packages\librosa\core\intervals.py:15: DeprecationWarning: path is deprecated. Use files() instead. Refer to https://importlib-resources.readthedocs.io/en/latest/using.html#migrating-from-legacy for migration advice.
  with resources.path("librosa.core", "intervals.msgpack") as imsgpack:
D:\forks\other\SHFLA\.venv\Lib\site-packages\audioread\rawread.py:16: DeprecationWarning: 'aifc' is deprecated and slated for removal in Python 3.13
  import aifc
D:\forks\other\SHFLA\.venv\Lib\site-packages\audioread\rawread.py:17: DeprecationWarning: 'audioop' is deprecated and slated for removal in Python 3.13
  import audioop
D:\forks\other\SHFLA\.venv\Lib\site-packages\audioread\rawread.py:19: DeprecationWarning: 'sunau' is deprecated and slated for removal in Python 3.13
  import sunau
D:\forks\other\SHFLA\main.py:228: ResourceWarning: unclosed file <_io.TextIOWrapper name='nul' mode='w' encoding='cp65001'>
  with contextlib.redirect_stdout(open(os.devnull, 'w')), contextlib.redirect_stderr(open(os.devnull, 'w')):
ResourceWarning: Enable tracemalloc to get the object allocation traceback
Pre-processing images for visualization...
⠏ Processing images... ----------------------------------------   0% 0:00:00
Traceback (most recent call last):
  File "D:\forks\other\SHFLA\main.py", line 380, in <module>
    main()
  File "D:\forks\other\SHFLA\main.py", line 341, in main
    process_chunk(i)
  File "D:\forks\other\SHFLA\main.py", line 318, in process_chunk
    image = gpu_julia_set(
            ^^^^^^^^^^^^^^
  File "D:\forks\other\SHFLA\main.py", line 136, in gpu_julia_set
    image_device = cuda.to_device(image_host)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\forks\other\SHFLA\.venv\Lib\site-packages\numba\cuda\cudadrv\devices.py", line 231, in _require_cuda_context
    with _runtime.ensure_context():
  File "C:\Users\bach_ar\AppData\Roaming\uv\python\cpython-3.12.5-windows-x86_64-none\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "D:\forks\other\SHFLA\.venv\Lib\site-packages\numba\cuda\cudadrv\devices.py", line 121, in ensure_context
    with driver.get_active_context():
  File "D:\forks\other\SHFLA\.venv\Lib\site-packages\numba\cuda\cudadrv\driver.py", line 495, in __enter__
    driver.cuCtxGetCurrent(byref(hctx))
    ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\forks\other\SHFLA\.venv\Lib\site-packages\numba\cuda\cudadrv\driver.py", line 295, in __getattr__
    raise CudaSupportError("Error at driver init: \n%s:" %
numba.cuda.cudadrv.error.CudaSupportError: Error at driver init:

CUDA driver library cannot be found.
If you are sure that a CUDA driver is installed,
try setting environment variable NUMBA_CUDA_DRIVER
with the file path of the CUDA driver shared library.
:
```

**Comment by Tetraslam** [comment]
Fixed and tested the CUDA detection, should work now. It takes ~1 minute on my laptop's CPU to load the default track (Only Shallow - My Bloody Valentine), but it runs smoothly post that.
